import type { Flight } from "@/lib/types";

export const mockFlights: Flight[] = [
  {
    id: "fl-001",
    airline: "Biman Bangladesh Airlines",
    airlineCode: "BG",
    airlineLogo: "/demo/biman-bd.png",
    flightNumber: "BG 147",
    from: { city: "Dhaka", code: "DAC", airport: "Hazrat Shahjalal International Airport", country: "Bangladesh" },
    to: { city: "Cox's Bazar", code: "CXB", airport: "Cox's Bazar Airport", country: "Bangladesh" },
    departure: "2026-07-04T07:30:00",
    arrival: "2026-07-04T08:35:00",
    duration: "1h 05m",
    stops: 0,
    price: 4500,
    originalPrice: 5800,
    currency: "BDT",
    cabinClass: "economy",
    baggage: "20 kg",
    carryOn: "7 kg",
    refundable: true,
    fareType: "Flexible",
    seatsLeft: 6,
    aircraft: "Boeing 737-800",
  },
  {
    id: "fl-002",
    airline: "US-Bangla Airlines",
    airlineCode: "BS",
    airlineLogo: "/demo/us-bangla.png",
    flightNumber: "BS 201",
    from: { city: "Dhaka", code: "DAC", airport: "Hazrat Shahjalal International Airport", country: "Bangladesh" },
    to: { city: "Cox's Bazar", code: "CXB", airport: "Cox's Bazar Airport", country: "Bangladesh" },
    departure: "2026-07-04T09:15:00",
    arrival: "2026-07-04T10:20:00",
    duration: "1h 05m",
    stops: 0,
    price: 3900,
    currency: "BDT",
    cabinClass: "economy",
    baggage: "20 kg",
    carryOn: "7 kg",
    refundable: false,
    fareType: "Standard",
    seatsLeft: 12,
    aircraft: "ATR 72-600",
  },
  {
    id: "fl-003",
    airline: "Novoair",
    airlineCode: "VQ",
    airlineLogo: "/demo/novoair.png",
    flightNumber: "VQ 933",
    from: { city: "Dhaka", code: "DAC", airport: "Hazrat Shahjalal International Airport", country: "Bangladesh" },
    to: { city: "Cox's Bazar", code: "CXB", airport: "Cox's Bazar Airport", country: "Bangladesh" },
    departure: "2026-07-04T11:40:00",
    arrival: "2026-07-04T12:45:00",
    duration: "1h 05m",
    stops: 0,
    price: 4200,
    originalPrice: 4800,
    currency: "BDT",
    cabinClass: "economy",
    baggage: "20 kg",
    carryOn: "7 kg",
    refundable: true,
    fareType: "Saver",
    seatsLeft: 3,
    aircraft: "ATR 72-500",
  },
  {
    id: "fl-004",
    airline: "Air Astra",
    airlineCode: "BG",
    airlineLogo: "/demo/air-astra.png",
    flightNumber: "BG 151",
    from: { city: "Dhaka", code: "DAC", airport: "Hazrat Shahjalal International Airport", country: "Bangladesh" },
    to: { city: "Cox's Bazar", code: "CXB", airport: "Cox's Bazar Airport", country: "Bangladesh" },
    departure: "2026-07-04T14:00:00",
    arrival: "2026-07-04T15:05:00",
    duration: "1h 05m",
    stops: 0,
    price: 5200,
    currency: "BDT",
    cabinClass: "business",
    baggage: "30 kg",
    carryOn: "10 kg",
    refundable: true,
    fareType: "Business Flex",
    seatsLeft: 4,
    aircraft: "Boeing 737-800",
  },
  {
    id: "fl-005",
    airline: "Biman Bangladesh Airlines",
    airlineCode: "BG",
    airlineLogo: "/demo/biman-bd.png",
    flightNumber: "BG 147",
    from: { city: "Dhaka", code: "DAC", airport: "Hazrat Shahjalal International Airport", country: "Bangladesh" },
    to: { city: "Cox's Bazar", code: "CXB", airport: "Cox's Bazar Airport", country: "Bangladesh" },
    departure: "2026-07-04T07:30:00",
    arrival: "2026-07-04T08:35:00",
    duration: "1h 05m",
    stops: 0,
    price: 4500,
    originalPrice: 5800,
    currency: "BDT",
    cabinClass: "economy",
    baggage: "20 kg",
    carryOn: "7 kg",
    refundable: true,
    fareType: "Flexible",
    seatsLeft: 6,
    aircraft: "Boeing 737-800",
  },
  {
    id: "fl-006",
    airline: "US-Bangla Airlines",
    airlineCode: "BS",
    airlineLogo: "/demo/us-bangla.png",
    flightNumber: "BS 201",
    from: { city: "Dhaka", code: "DAC", airport: "Hazrat Shahjalal International Airport", country: "Bangladesh" },
    to: { city: "Cox's Bazar", code: "CXB", airport: "Cox's Bazar Airport", country: "Bangladesh" },
    departure: "2026-07-04T09:15:00",
    arrival: "2026-07-04T10:20:00",
    duration: "1h 05m",
    stops: 0,
    price: 3900,
    currency: "BDT",
    cabinClass: "economy",
    baggage: "20 kg",
    carryOn: "7 kg",
    refundable: false,
    fareType: "Standard",
    seatsLeft: 12,
    aircraft: "ATR 72-600",
  },
  {
    id: "fl-007",
    airline: "Novoair",
    airlineCode: "VQ",
    airlineLogo: "/demo/novoair.png",
    flightNumber: "VQ 933",
    from: { city: "Dhaka", code: "DAC", airport: "Hazrat Shahjalal International Airport", country: "Bangladesh" },
    to: { city: "Cox's Bazar", code: "CXB", airport: "Cox's Bazar Airport", country: "Bangladesh" },
    departure: "2026-07-04T11:40:00",
    arrival: "2026-07-04T12:45:00",
    duration: "1h 05m",
    stops: 0,
    price: 4200,
    originalPrice: 4800,
    currency: "BDT",
    cabinClass: "economy",
    baggage: "20 kg",
    carryOn: "7 kg",
    refundable: true,
    fareType: "Saver",
    seatsLeft: 3,
    aircraft: "ATR 72-500",
  },
  {
    id: "fl-008",
    airline: "Air Astra",
    airlineCode: "BG",
    airlineLogo: "/demo/air-astra.png",
    flightNumber: "BG 151",
    from: { city: "Dhaka", code: "DAC", airport: "Hazrat Shahjalal International Airport", country: "Bangladesh" },
    to: { city: "Cox's Bazar", code: "CXB", airport: "Cox's Bazar Airport", country: "Bangladesh" },
    departure: "2026-07-04T14:00:00",
    arrival: "2026-07-04T15:05:00",
    duration: "1h 05m",
    stops: 0,
    price: 5200,
    currency: "BDT",
    cabinClass: "business",
    baggage: "30 kg",
    carryOn: "10 kg",
    refundable: true,
    fareType: "Business Flex",
    seatsLeft: 4,
    aircraft: "Boeing 737-800",
  },
  
];

export const popularRoutes = [
  { from: "DAC", to: "CXB", fromCity: "Dhaka", toCity: "Cox's Bazar" },
  { from: "DAC", to: "DXB", fromCity: "Dhaka", toCity: "Dubai" },
  { from: "DAC", to: "BKK", fromCity: "Dhaka", toCity: "Bangkok" },
  { from: "DAC", to: "KUL", fromCity: "Dhaka", toCity: "Kuala Lumpur" },
  { from: "DAC", to: "SIN", fromCity: "Dhaka", toCity: "Singapore" },
  { from: "DAC", to: "DEL", fromCity: "Dhaka", toCity: "Delhi" },
];
