import type { Hotel } from "@/lib/types";

export const mockHotels: Hotel[] = [
  {
    id: "ht-001",
    name: "The Peninsula Cox's Bazar",
    description:
      "Experience luxury beachfront living at The Peninsula, where the world's longest natural sandy beach meets world-class hospitality. Enjoy breathtaking ocean views, a rooftop infinity pool, and authentic Bangladeshi cuisine.",
    address: "Kolatoli Beach Road, Cox's Bazar",
    city: "Cox's Bazar",
    country: "Bangladesh",
    location: "Kolatoli Beach, Cox's Bazar",
    rating: 4.8,
    reviewCount: 1240,
    starCategory: 5,
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800",
    ],
    amenities: ["Free WiFi", "Infinity Pool", "Spa", "Restaurant", "Beach Access", "Gym", "Room Service", "Airport Shuttle"],
    pricePerNight: 12500,
    originalPrice: 16000,
    currency: "BDT",
    breakfast: true,
    freeCancellation: true,
    distanceFromCenter: 0.8,
    tags: ["Beachfront", "Luxury", "Pool"],
  },
  {
    id: "ht-002",
    name: "Long Beach Hotel",
    description:
      "A comfortable and affordable retreat steps from Cox's Bazar beach. Perfect for families and couples seeking relaxation with stunning sea views and modern amenities.",
    address: "Hotel Zone, Cox's Bazar",
    city: "Cox's Bazar",
    country: "Bangladesh",
    location: "Hotel Zone, Cox's Bazar",
    rating: 4.3,
    reviewCount: 856,
    starCategory: 4,
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800",
      "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800",
    ],
    amenities: ["Free WiFi", "Swimming Pool", "Restaurant", "Sea View", "Parking", "Room Service"],
    pricePerNight: 6800,
    originalPrice: 8500,
    currency: "BDT",
    breakfast: true,
    freeCancellation: true,
    distanceFromCenter: 1.2,
    tags: ["Sea View", "Family Friendly"],
  },
  {
    id: "ht-003",
    name: "Royal Tulip Sea Pearl Beach Resort",
    description:
      "Cox's Bazar's premier resort offering an unparalleled blend of luxury, comfort, and natural beauty. Set on a pristine beachfront with multiple dining options and a private beach.",
    address: "Inani Beach, Cox's Bazar",
    city: "Cox's Bazar",
    country: "Bangladesh",
    location: "Inani Beach, Cox's Bazar",
    rating: 4.6,
    reviewCount: 2105,
    starCategory: 5,
    images: [
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800",
      "https://images.unsplash.com/photo-1586611292717-f828b167408c?w=800",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800",
    ],
    amenities: ["Free WiFi", "Private Beach", "2 Pools", "Spa", "5 Restaurants", "Kids Club", "Gym", "Tennis Court"],
    pricePerNight: 15000,
    originalPrice: 19000,
    currency: "BDT",
    breakfast: true,
    freeCancellation: false,
    distanceFromCenter: 2.5,
    tags: ["Private Beach", "Luxury", "Resort"],
  },
  {
    id: "ht-004",
    name: "Sayeman Beach Resort",
    description:
      "A charming boutique resort nestled between lush greenery and the golden sands of Cox's Bazar. Offering a tranquil escape with personalized service and eco-friendly practices.",
    address: "Kolatoli, Cox's Bazar",
    city: "Cox's Bazar",
    country: "Bangladesh",
    location: "Kolatoli, Cox's Bazar",
    rating: 4.1,
    reviewCount: 634,
    starCategory: 4,
    images: [
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800",
      "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=800",
    ],
    amenities: ["Free WiFi", "Pool", "Garden", "Restaurant", "Beach Access", "Yoga"],
    pricePerNight: 5200,
    currency: "BDT",
    breakfast: false,
    freeCancellation: true,
    distanceFromCenter: 1.8,
    tags: ["Boutique", "Eco-friendly"],
  },
  {
    id: "ht-005",
    name: "Grand Sultan Tea Resort & Golf",
    description:
      "Nestled amidst the rolling tea gardens of Sylhet, Grand Sultan offers a unique highland resort experience. With a championship golf course, luxury villas, and panoramic tea garden views.",
    address: "Rashidpur, Srimangal, Sylhet",
    city: "Sylhet",
    country: "Bangladesh",
    location: "Tea Gardens, Srimangal",
    rating: 4.7,
    reviewCount: 980,
    starCategory: 5,
    images: [
      "https://images.unsplash.com/photo-1540541338537-71acba6e4e7f?w=800",
      "https://images.unsplash.com/photo-1416820000452-d89bb6e4e3a0?w=800",
    ],
    amenities: ["Free WiFi", "Golf Course", "Spa", "Pool", "Restaurant", "Tea Garden Tours", "Gym"],
    pricePerNight: 18000,
    originalPrice: 22000,
    currency: "BDT",
    breakfast: true,
    freeCancellation: true,
    distanceFromCenter: 4.0,
    tags: ["Golf", "Tea Garden", "Luxury"],
  },
  {
    id: "ht-006",
    name: "Radisson Blu Dhaka Water Garden",
    description:
      "Dhaka's iconic five-star hotel set within beautifully landscaped water gardens. Offering sophisticated rooms, world-class dining, and a prime location near Gulshan business district.",
    address: "Airport Road, Gulshan, Dhaka",
    city: "Dhaka",
    country: "Bangladesh",
    location: "Gulshan, Dhaka",
    rating: 4.5,
    reviewCount: 1876,
    starCategory: 5,
    images: [
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800",
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800",
    ],
    amenities: ["Free WiFi", "Pool", "Spa", "Business Center", "Multiple Restaurants", "Gym", "Airport Shuttle"],
    pricePerNight: 22000,
    currency: "BDT",
    breakfast: true,
    freeCancellation: true,
    distanceFromCenter: 3.2,
    tags: ["Business", "Luxury", "City Center"],
  },
];

export const hotelAmenityIcons: Record<string, string> = {
  "Free WiFi": "wifi",
  "Pool": "waves",
  "Infinity Pool": "waves",
  "2 Pools": "waves",
  "Spa": "sparkles",
  "Restaurant": "utensils",
  "Beach Access": "umbrella",
  "Private Beach": "umbrella",
  "Gym": "dumbbell",
  "Room Service": "bell",
  "Airport Shuttle": "car",
  "Parking": "car",
  "Sea View": "eye",
  "Kids Club": "baby",
  "Tennis Court": "activity",
  "Golf Course": "flag",
  "Garden": "leaf",
  "Yoga": "activity",
  "Business Center": "briefcase",
};
